export const USER_ACTION_TYPES = {
    REGISTER_START: "user/REGISTER_START",
    REGISTER_SUCCESS: "user/REGISTER_SUCCESS",
    REGISTER_FAILED: "user/REGISTER_FAILED",
    USER_LOAD_START: "user/USER_LOAD_START",
    USER_LOADED: "user/USER_LOADED",
    USER_LOAD_FAILED: "user/USER_LOAD_FAILED",
    AUTH_ERROR: "user/AUTH_ERROR",
    LOGIN_START: "user/LOGIN_START",
    LOGIN_SUCCESS: "user/LOGIN_SUCCESS",
    LOGIN_FAILED: "user/LOGIN_FAILED",
    LOGOUT: "user/LOGOUT",
};
