export const TWEET_ACTION_TYPES = {
    FETCH_TWEETS_START: "tweet/FETCH_TWEETS_START",
    FETCH_TWEETS_SUCCESS: "tweet/FETCH_TWEETS_SUCCESS",
    FETCH_TWEETS_FAILED: "tweet/FETCH_TWEETS_FAILED",
    SEND_TWEET_START: "tweet/SEND_TWEET_START",
    SEND_TWEET_SUCCESS: "tweet/SEND_TWEET_SUCCESS",
    SEND_TWEET_FAILED: "tweet/SEND_TWEET_FAILED",
    FETCH_TWEET_START: "tweet/FETCH_TWEET_START",
    FETCH_TWEET_SUCCESS: "tweet/FETCH_TWEET_SUCCESS",
    FETCH_TWEET_FAILED: "tweet/FETCH_TWEET_FAILED",
    EXIT_PAGE: "tweet/EXIT_PAGE",
};
