export const TWEET_ACTION_TYPES = {
    FETCH_TWEET_START: "tweet/FETCH_TWEET_START",
    FETCH_TWEET_SUCCESS: "tweet/FETCH_TWEET_SUCCESS",
    FETCH_TWEET_FAILED: "tweet/FETCH_TWEET_FAILED",
    SEND_TWEET_START: "tweet/SEND_TWEET_START",
    SEND_TWEET_SUCCESS: "tweet/SEND_TWEET_SUCCESS",
    SEND_TWEET_FAILED: "tweet/SEND_TWEET_FAILED",
};
