export const LIKE_ACTION_TYPES = {
    LIKE_TWEET_SUCCESS: "tweet/LIKE_TWEETS_SUCCESS",
    LIKE_TWEET_FAILED: "tweet/LIKE_TWEETS_FAILED",
    UNLIKE_TWEET_SUCCESS: "tweet/UNLIKE_TWEET_SUCCESS",
    UNLIKE_TWEET_FAILED: "tweet/UNLIKE_TWEET_FAILED",
};
