import Tweet from "../tweets/Tweet";

const TweetReplies = () => {
    return (
        <div>
            <div>
                {/* <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                />
                <Tweet
                    id={1}
                    text={"Text"}
                    userId={1}
                    username={"username"}
                    name={"name"}
                /> */}
            </div>
        </div>
    );
};

export default TweetReplies;
